version: "3"
services:
  openwebrx:
    image: jketterl/openwebrx-soapyremote:stable
    volumes:
      - /docker/openwebrx/settings:/var/lib/openwebrx
    ports:
      - 8073:8073
    #devices:
    #  - /dev/bus/usb/002/002:/dev/bus/usb/002/002
    tmpfs:
      - /tmp/openwebrx
    env_file:
      - .env
